eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: file-server:7001  #指定服务的id
server:
  port: 7000

spring:
  application:
    name: file-server

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin1234
  secretKey: admin1234




