server:
  port: 7001

#服务名称
spring:
  application:
    name: job-server
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/myself?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5  # 初始化时建立物理连接的个数
      max-active:  10 #最大连接数是10
      min-idle: 10 #最小连接数是5
      max-wait: 30000 #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#数据源

# eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/ #注册中心地址
  instance:
    instance-id: job-server:7000
    prefer-ip-address: true #指定服务的id



#日志
logging:
  config: classpath:logback.xml

#xxl.job配置信息
xxl:
  job:
    admin:
      #调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #执行器通讯TOKEN [选填]：非空时启用
    accessToken:
    executor:
      #执行器心跳注册分组依据；为空则关闭自动注册
      appname: actor
      #优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题
      address:
      ip: 10.139.115.50
      port: 9998
      #需要对该路径拥有读写权限；为空则使用默认路径
      logpath:
      #过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30




