eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: resource1-server:4000  #指定服务的id
server:
  port: 4001
spring:
  application:
    name: resource1-server
  datasource:
    druid:
      username: root
      password: password
      url: jdbc:mysql://127.0.0.1:3306/myself?characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      #启动程序时，在连接池中初始化多少个连接
      initial-size: 5
      #连接池中最多支持多少个活动会话
      max-active: 30
      #回收空闲连接时，将保证至少有minIdle个连接
      min-idle: 5
      #程序向连接池中请求连接时,超过maxWait的值后，认为本次请求失败，即连接池
      max-wait: 300000
      #检查空闲连接的频率，单位毫秒, 非正整数时表示不进行检查
      time-between-eviction-runs-millis: 6000000
      #配置jdbcType 参数为指定类型
      #rabbitmq
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual #mq手动确认
      simple:
        acknowledge-mode: manual #手动确认
        retry:
          enabled: true #支持重试
    publisher-confirm-type: correlated #开启确认模式
    publisher-returns: true #开启回退
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null

#日志
logging:
  config: classpath:logback.xml




