eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: file-server:10001  #指定服务的id


server:
  port: 10001

spring:
  application:
    name: netty-server
